### ISSUE TITLE
MC6840?

### ISSUE THREAD

**Issue by JNSpears** [raybellis/usim#11]
Has anyone implemented a device for the MC6840?

**Comment by raybellis** [comment]
I haven't (since it doesn't appear in any device I use) but it probably wouldn't be that hard.

There's a 6522 timer implementation in a (currently private) project that I'm involved with, and the approach taken there to implement timers is to count the number of cycles elapsed in the device's `tick` function.   The emulated CPU frequency is kept roughly in sync with the real system's clock frequency by other parts of the system.

If actual elapsed time is important you'd need to use host system timers instead.

**Comment by JNSpears** [comment]
A 6522 would work, I don't have a real timer in my system and that might be
easier to come by. I have been developing extensions to the old Percom MPX9
os it ran, wanted to include multitasking hence the timer question.
--James
